(cl:defpackage rosSimpleStep-srv
  (:use )
  (:export
   "SRVJOINTSTATE"
   "<SRVJOINTSTATE-REQUEST>"
   "SRVJOINTSTATE-REQUEST"
   "<SRVJOINTSTATE-RESPONSE>"
   "SRVJOINTSTATE-RESPONSE"
   "SRVCALIBRATE"
   "<SRVCALIBRATE-REQUEST>"
   "SRVCALIBRATE-REQUEST"
   "<SRVCALIBRATE-RESPONSE>"
   "SRVCALIBRATE-RESPONSE"
   "SRVPARK"
   "<SRVPARK-REQUEST>"
   "SRVPARK-REQUEST"
   "<SRVPARK-RESPONSE>"
   "SRVPARK-RESPONSE"
   "SRVSETZERO"
   "<SRVSETZERO-REQUEST>"
   "SRVSETZERO-REQUEST"
   "<SRVSETZERO-RESPONSE>"
   "SRVSETZERO-RESPONSE"
  ))

